service: yodalambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256

functions:
  advice:
    handler: advice.handle
    events:
      - sqs: YOUR ARN SQS
